### ISSUE TITLE
Various Errors Occuring Randomly

### ISSUE THREAD

**Issue by veysiadn** [andpp/BM-Lite#1]
Hello, I was trying to implement the same application on STM32U575 based microcontroller. Enrollment and identification procedure works fine initially. After some testing it fails and gets random errors such as IO errors, CRC errors, General Error etc.
I used the same structure that is implemented here. 
My test code lies in the link below  and the driver code is in Drivers/Modules folder.
https://github.com/veysiadn/fp-reader-test-base/ 

Thanks in advance.

Kind regards,
Veysi

**Comment by andpp** [comment]
In most of the cases IO errors are caused ether by incorrect configuration of a serial port of some noise on the line. Could you please verify by oscilloscope that serail port configuration is correct and that the is no issues with the signals on the lines.

**Comment by veysiadn** [comment]
The serial port configuration is the same as the example code provided here, but I will check if there's some noise on the line to make sure it's related to noise.

**Comment by veysiadn** [comment]
![SCR06](https://github.com/andpp/BM-Lite/assets/52937922/d523b85b-feea-45c5-9115-dc0aeaf93bd6)
![SCR07](https://github.com/andpp/BM-Lite/assets/52937922/a803345d-b8fa-44b1-b98d-6678d49923ed)

Green is Tx and Yellow is Rx on those images, I don't see any noise, it seems like they're all clean square waves. 
The interesting part while testing it was that the initialization and checking the firmware version always worked fine.
Errors occur when identifying finger or enrolling finger functions are called.  I'm assuming the MCU on the sensor is communicating fine when the fingerprint sensor is not activated/working. When the sensor functionality is called things become a little bit messy.
I also tried the Python code provided by the company, there I saw errors like those in the picture below:
where I got errors like 
**host_cmd_handle_command - error: -8!, 
host_cmd_handle_command - timeout!**
![image](https://github.com/andpp/BM-Lite/assets/52937922/c605bc42-a1e2-4746-b700-a4367c301765)
![image](https://github.com/andpp/BM-Lite/assets/52937922/b0039628-0c3b-49ca-bf7f-6406cbd60b67)

These errors are random, they're not occurring all the time, and when I reset it doesn't recover directly, in some cases, I need to reset several times until it recovers. 

Do you have any recommendations or some info that I might not be aware of?
